version: '3.9'

services:
  db:
    image: postgres
    container_name: fastapi-marvel-db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: fastapi-marvel-app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://youruser:yourpassword@db/yourdb"
